
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 9600
board_build.flash_mode = opi
board_build.flash_size = 512KB
lib_deps = adafruit/Adafruit NeoPixel@^1.12.5

; # 关键配置修改
; build_flags = 
;     -DCORE_DEBUG_LEVEL=0
;     -DLOG_DEFAULT_LEVEL=0         ; 关闭 ESP-IDF 默认日志
;     -DCONFIG_LOG_DEFAULT_LEVEL=0  ; 强制设置日志级别为 NONE
;     -DCONFIG_BOOTLOADER_LOG_LEVEL=0 ; 关闭 Bootloader 日志

; # 添加自定义 sdkconfig 覆盖默认配置
; board_build.sdkconfig = 
;     CONFIG_LOG_DEFAULT_LEVEL_NONE=y
;     CONFIG_BOOTLOADER_LOG_LEVEL_NONE=y
# 
; board_build.partitions = partition.csv